# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera

PRODUCT_PACKAGES += \
    MiuiCamera \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmicampostproc_client \
    libgui_shim_miuicamera \
    vendor.xiaomi.hardware.campostproc@1.0
